export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FETCH_POSTS_USER_ID = 'FETCH_POSTS_USER_ID';
export const FETCH_POSTS_USER_ID_SUCCESS = 'FETCH_POSTS_USER_ID_SUCCESS';
export const FETCH_POSTS_USER_ID_FAIL = 'FETCH_POSTS_USER_ID_FAIL';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const FETCH_ROOMS = 'FETCH_ROOMS';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_FAIL = 'FETCH_ROOMS_FAIL';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL';

export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const CREATE_EMOJI = 'CREATE_EMOJI';
export const CREATE_EMOJI_SUCCESS = 'CREATE_EMOJI_SUCCESS';
export const CREATE_EMOJI_FAIL = 'CREATE_EMOJI_FAIL';

export const UPDATE_EMOJI = 'UPDATE_EMOJI';
export const UPDATE_EMOJI_SUCCESS = 'UPDATE_EMOJI_SUCCESS';
export const UPDATE_EMOJI_FAIL = 'UPDATE_EMOJI_FAIL';

export const DELETE_EMOJI = 'DELTE_EMOJI';
export const DELETE_EMOJI_SUCCESS = 'DELTE_EMOJI_SUCCESS';
export const DELETE_EMOJI_FAIL = 'DELTE_EMOJI_FAIL';

export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_RECEIVED_SUCCESS = 'POSTS_RECEIVED_SUCCESS';
export const POSTS_RECEIVED_FAIL = 'POSTS_RECEIVED_FAIL';

export const COMMENTS_RECEIVED = 'COMMENTS_RECEIVED';
export const COMMENTS_RECEIVED_SUCCESS = 'COMMENTS_RECEIVED_SUCCESS';
export const COMMENTS_RECEIVED_FAIL = 'COMMENTS_RECEIVED_FAIL';

export const MESSAGES_RECEIVED = 'MESSAGES_RECEIVED';
export const MESSAGES_RECEIVED_SUCCESS = 'MESSAGES_RECEIVED_SUCCESS';
export const MESSAGES_RECEIVED_FAIL = 'MESSAGES_RECEIVED_FAIL';

export const COMMENTS_COUNT_CHANGE = 'COMMENTS_COUNT_CHANGE';

export const EMOJIS_COUNT_CHANGE = 'EMOJIS_COUNT_CHANGE';

export const CHECK_USER ='CHECK_USER'
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS'
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL'

export const CREATE_USER ='CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const FETCH_USER ='FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const FETCH_FOLLOWERS ='FETCH_FOLLOWERS'
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS'
export const FETCH_FOLLOWERS_FAIL = 'FETCH_FOLLOWERS_FAIL'

export const FETCH_FOLLOWINGS ='FETCH_FOLLOWINGS'
export const FETCH_FOLLOWINGS_SUCCESS = 'FETCH_FOLLOWINGS_SUCCESS'
export const FETCH_FOLLOWINGS_FAIL = 'FETCH_FOLLOWINGS_FAIL'

export const CREATE_FOLLOW ='CREATE_FOLLOW'
export const CREATE_FOLLOW_SUCCESS = 'CREATE_FOLLOW_SUCCESS'
export const CREATE_FOLLOW_FAIL = 'CREATE_FOLLOW_FAIL'

export const DELETE_FOLLOW ='DELETE_FOLLOW'
export const DELETE_FOLLOW_SUCCESS = 'DELETE_FOLLOW_SUCCESS'
export const DELETE_FOLLOW_FAIL = 'DELETE_FOLLOW_FAIL'

export const UPDATE_ROOM = 'UPDATE_ROOM'

export const FIND_USERS ='FIND_USERS'
export const FIND_USERS_SUCCESS = 'FIND_USERS_SUCCESS'
export const FIND_USERS_FAIL = 'FIND_USERS_FAIL'


