export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FETCH_POSTS_USER_ID = 'FETCH_POSTS_USER_ID';
export const FETCH_POSTS_USER_ID_SUCCESS = 'FETCH_POSTS_USER_ID_SUCCESS';
export const FETCH_POSTS_USER_ID_FAIL = 'FETCH_POSTS_USER_ID_FAIL';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const CREATE_EMOJI = 'CREATE_EMOJI';
export const CREATE_EMOJI_SUCCESS = 'CREATE_EMOJI_SUCCESS';
export const CREATE_EMOJI_FAIL = 'CREATE_EMOJI_FAIL';

export const UPDATE_EMOJI = 'UPDATE_EMOJI';
export const UPDATE_EMOJI_SUCCESS = 'UPDATE_EMOJI_SUCCESS';
export const UPDATE_EMOJI_FAIL = 'UPDATE_EMOJI_FAIL';

export const DELETE_EMOJI = 'DELTE_EMOJI';
export const DELETE_EMOJI_SUCCESS = 'DELTE_EMOJI_SUCCESS';
export const DELETE_EMOJI_FAIL = 'DELTE_EMOJI_FAIL';

export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_RECEIVED_SUCCESS = 'POSTS_RECEIVED_SUCCESS';
export const POSTS_RECEIVED_FAIL = 'POSTS_RECEIVED_FAIL';

export const COMMENTS_RECEIVED = 'COMMENTS_RECEIVED';
export const COMMENTS_RECEIVED_SUCCESS = 'COMMENTS_RECEIVED_SUCCESS';
export const COMMENTS_RECEIVED_FAIL = 'COMMENTS_RECEIVED_FAIL';

export const COMMENTS_COUNT_CHANGE = 'COMMENTS_COUNT_CHANGE';

export const EMOJIS_COUNT_CHANGE = 'EMOJIS_COUNT_CHANGE';

export const CHECK_USER ='CHECK_USER'
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS'
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL'

export const CREATE_USER ='CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const FETCH_USER ='FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'